from __future__ import annotations

from radar.db import add_evidence, rows, upsert_opportunity
from radar.scoring import score_opportunity

SEEDS = [
    {
        "vertical":"Government", "use_case":"sovereign citizen-data processing", "technology":"sovereign cloud and AI enclaves", "geography":"Belgium / Europe", "orange_domain":"Cloud and AI", "persona":"Strategy",
        "signal_type":"regulation", "horizon":"Now", "why_hot_now":"European sovereignty, regulatory compliance, and trusted AI requirements are converging around public-sector data workloads.",
        "why_it_matters":"Orange Business positions secure cloud orchestration, Cloud Avenue, and trusted digital services as strategic capabilities.", "next_action":"Run a Belgian public-sector discovery workshop and validate two active procurement or regulatory signals.",
        "af":{"market_signal":8,"source_diversity":7,"evidence_quality":8,"momentum":8,"strategic_relevance":10}, "rtw":{"offering_fit":9,"customer_overlap":7,"references":5,"partner_readiness":8},
        "evidence":[
            {"source_name":"Orange Business Corporate Presentation 2026","source_url":"local://Aorangeresearch/OB_Corporate-Presentation-2026#slide-18","source_domain":"orange-owned","published_at":"2026-01-01","signal_type":"proof_signal","claim":"Cloud Avenue is presented with sovereignty, regulatory compliance, and generative AI positioning.","quality":8},
            {"source_name":"Orange Innovation Radar Brief","source_url":"local://Aorangeresearch/innovation-radar-brief#page-18","source_domain":"orange-owned","published_at":"2026-01-01","signal_type":"market_trend","claim":"The brief identifies sovereign cloud and AI enclaves for government citizen data as a candidate requiring external validation.","quality":6}
        ]
    },
    {
        "vertical":"Banking", "use_case":"secure WAN threat visibility", "technology":"network-as-a-sensor security analytics", "geography":"Belgium / Europe", "orange_domain":"Cybersecurity", "persona":"Presales",
        "signal_type":"technology_maturity", "horizon":"Next", "why_hot_now":"Encrypted traffic, distributed work, and converged network-security operations increase demand for telemetry generated by connectivity infrastructure.",
        "why_it_matters":"The concept combines Orange Business secure connectivity with Orange Cyberdefense capabilities, but banking demand still needs independent validation.", "next_action":"Build a presales hypothesis with one banking account and collect a named deployment plus a buyer signal.",
        "af":{"market_signal":7,"source_diversity":6,"evidence_quality":6,"momentum":7,"strategic_relevance":10}, "rtw":{"offering_fit":9,"customer_overlap":6,"references":4,"partner_readiness":8},
        "evidence":[
            {"source_name":"Orange Business Corporate Presentation 2026","source_url":"local://Aorangeresearch/OB_Corporate-Presentation-2026#slide-17","source_domain":"orange-owned","published_at":"2026-01-01","signal_type":"proof_signal","claim":"NextGen Secured Connectivity is listed as an Orange Business strategic value proposition.","quality":8},
            {"source_name":"Orange Innovation Radar Brief","source_url":"local://Aorangeresearch/innovation-radar-brief#candidate","source_domain":"orange-owned","published_at":"2026-01-01","signal_type":"market_trend","claim":"Network-as-a-sensor analytics for banking WANs is an unvalidated candidate in the provided backlog.","quality":5}
        ]
    },
    {
        "vertical":"Manufacturing", "use_case":"product traceability and compliance", "technology":"digital product passports", "geography":"Europe", "orange_domain":"Smart industries", "persona":"Sales",
        "signal_type":"regulation", "horizon":"Next", "why_hot_now":"Digital product passport obligations create a potential compliance trigger for manufacturers and their supply chains.",
        "why_it_matters":"The use case may combine connected products, IoT, integration, and data platforms, but Orange-specific proof is incomplete.", "next_action":"Validate the applicable EU deadlines, interview two Belgian manufacturers, and identify an implementation partner.",
        "af":{"market_signal":8,"source_diversity":5,"evidence_quality":7,"momentum":8,"strategic_relevance":7}, "rtw":{"offering_fit":6,"customer_overlap":6,"references":3,"partner_readiness":5},
        "evidence":[
            {"source_name":"Orange Business Corporate Presentation 2026","source_url":"local://Aorangeresearch/OB_Corporate-Presentation-2026#slide-17-smart-products","source_domain":"orange-owned","published_at":"2026-01-01","signal_type":"proof_signal","claim":"Smart connected products and smart manufacturing are listed among Orange Business value propositions.","quality":8},
            {"source_name":"Orange Innovation Radar Brief","source_url":"local://Aorangeresearch/innovation-radar-brief#dpp","source_domain":"orange-owned","published_at":"2026-01-01","signal_type":"regulation","claim":"Digital product passports and traceability are supplied as a candidate hypothesis, not validated evidence.","quality":5}
        ]
    }
]


def seed_demo() -> int:
    if rows("SELECT id FROM opportunities LIMIT 1"):
        return 0
    for item in SEEDS:
        domains = {e["source_domain"] for e in item["evidence"]}
        score = score_opportunity(item["af"], item["rtw"], len(item["evidence"]), len(domains))
        opportunity_id = upsert_opportunity({
            "slug":"-".join((item["vertical"],item["use_case"],item["technology"])).lower().replace(" ","-"), "title":f"{item['vertical']} x {item['use_case']} x {item['technology']}",
            **{key:item[key] for key in ("vertical","use_case","technology","geography","orange_domain","persona","signal_type","horizon","why_hot_now","why_it_matters","next_action")},
            "attractiveness":score.attractiveness,"right_to_win":score.right_to_win,"confidence":score.confidence,"status":score.status,"score_rationale":score.rationale,
            "factors_json":{"attractiveness":item["af"],"right_to_win":item["rtw"],"rationales":{"note":"Seed scores are hypotheses for demonstration and must be replaced by external evidence."},"classification":{"urgency":9 if item["horizon"] == "Now" else 6,"signal_type":item["signal_type"],"horizon_rule":"Seeded demonstration classification from the supplied Orange hypothesis; not independently validated.","horizon_assigned_by":"Seed fixture"}}
        })
        for evidence in item["evidence"]:
            add_evidence(opportunity_id, evidence)
    return len(SEEDS)
